# Generated by Django 6.0.2 on 2026-02-11 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0004_purchaseline_tipo_pago'),
        ('finanzas', '0002_financeapproval_enviado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeapproval',
            name='aprobado_en',
        ),
        migrations.RemoveField(
            model_name='financeapproval',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='financeapproval',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='financeapproval',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_approvals_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financeapproval',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='financeapproval',
            name='purchase_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_approval', to='compras_oil.purchaserequest'),
        ),
        migrations.CreateModel(
            name='FinanceApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado para pagar'), ('PROGRAMADO', 'Programado'), ('EN_ESPERA', 'En espera'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('nota_admin', models.TextField(blank=True)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.financeapproval')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_line_decisions', to=settings.AUTH_USER_MODEL)),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_line_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_line', to='compras_oil.purchaseline')),
            ],
            options={
                'indexes': [models.Index(fields=['decision'], name='finanzas_fi_decisio_b065bd_idx'), models.Index(fields=['pagado'], name='finanzas_fi_pagado_815721_idx'), models.Index(fields=['scheduled_date'], name='finanzas_fi_schedul_2d30a2_idx')],
            },
        ),
    ]
