# Generated by Django 6.0.2 on 2026-02-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_remove_financeapproval_aprobado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeapproval',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
