# Generated by Django 6.0.2 on 2026-05-01 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0005_purchaseline_bom_item'),
        ('finanzas', '0004_alter_financeapproval_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=80, verbose_name='Número factura proveedor')),
                ('fecha_factura_proveedor', models.DateField(blank=True, null=True, verbose_name='Fecha factura proveedor')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_creadas', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='compras_oil.purchaserequest', verbose_name='Solicitud de compra')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='compras_oil.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar proveedor',
                'verbose_name_plural': 'Cuentas por pagar proveedores',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha abono')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor abonado')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='Referencia / comprobante')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_creados', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='finanzas.supplierinvoice', verbose_name='Factura proveedor')),
            ],
            options={
                'verbose_name': 'Abono proveedor',
                'verbose_name_plural': 'Abonos proveedores',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier'], name='finanzas_su_supplie_4910e8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['purchase_request'], name='finanzas_su_purchas_94a40e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['numero_factura_proveedor'], name='finanzas_su_numero__9631a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('supplier', 'purchase_request')},
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['fecha'], name='finanzas_su_fecha_752a31_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier_invoice'], name='finanzas_su_supplie_4b2c53_idx'),
        ),
    ]
