# Generated by Django 6.0.2 on 2026-05-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_supplierinvoice_supplierpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeapprovalline',
            name='tipo_operacion',
            field=models.CharField(choices=[('SERVICIO', 'Servicio'), ('COMPRA', 'Compra')], default='COMPRA', max_length=20),
        ),
    ]
