# Generated by Django 6.0.2 on 2026-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_financeapprovalline_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeapprovalline',
            name='tipo_operacion',
            field=models.CharField(choices=[('COMPRA', 'Compra - retención 2.5%'), ('SERVICIO', 'Servicio - retención 4%'), ('NA', 'N/A - sin retención')], default='COMPRA', max_length=20),
        ),
    ]
