# Generated by Django 6.0.2 on 2026-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_financeapprovalline_tipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='aplica_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='tipo_operacion',
            field=models.CharField(choices=[('COMPRA', 'Compra - retención 2.5%'), ('SERVICIO', 'Servicio - retención 4%'), ('NA', 'N/A - sin retención')], default='COMPRA', max_length=20),
        ),
    ]
