# Generated by Django 6.0.2 on 2026-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_supplierinvoice_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='tipo_operacion',
            field=models.CharField(choices=[('COMPRA', 'Compra - retención 2.5%'), ('SERVICIO', 'Servicio - retención 4%'), ('CARGA', 'Carga - retención 1%'), ('PASAJERO', 'Pasajero - retención 3.5%'), ('NA', 'N/A - sin retención')], default='COMPRA', max_length=20),
        ),
    ]
