# Generated by Django 6.0.2 on 2026-02-05 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom', '0003_alter_bomtemplateitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bom', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='bom.bom')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_compra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(blank=True, max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones_compras', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras_oil.purchaserequest')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras_oil.supplier')),
            ],
        ),
    ]
