# Generated by Django 6.0.2 on 2026-02-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='cantidad_a_comprar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
