# Generated by Django 6.0.2 on 2026-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0002_purchaseline_cantidad_a_comprar'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='observaciones_bom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='paw_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='paw_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='banco',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20),
        ),
    ]
