# Generated by Django 6.0.2 on 2026-02-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0003_purchaseline_observaciones_bom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='tipo_pago',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], default='CREDITO', max_length=20),
        ),
    ]
