# Generated by Django 6.0.2 on 2026-02-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_alter_bomtemplateitem_unique_together_and_more'),
        ('compras_oil', '0004_purchaseline_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='bom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='bom.bomitem'),
        ),
    ]
