# Generated by Django 6.0.2 on 2026-05-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0005_purchaseline_bom_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='porcentaje_pago',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Ej: 50 para 50%, 100 para 100%', max_digits=5),
        ),
    ]
