# Generated by Django 6.0.2 on 2026-05-05 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0006_purchaseline_porcentaje_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='porcentaje_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 para N/A, 50 para anticipo, 100 para pago completo', max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='tipo_pago',
            field=models.CharField(choices=[('NA', 'N/A'), ('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('NA', 'N/A'), ('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], max_length=20),
        ),
    ]
