# Generated by Django 6.0.2 on 2026-02-10 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras_oil', '0003_purchaseline_observaciones_bom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_inventario', to='compras_oil.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReceptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20)),
                ('observacion_inventario', models.TextField(blank=True)),
                ('purchase_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_linea', to='compras_oil.purchaseline')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.inventoryreception')),
            ],
        ),
    ]
