# Generated by Django 6.0.2 on 2026-02-12 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0004_purchaseline_tipo_pago'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_taller_creadas', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega_taller', to='compras_oil.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.workshopdelivery')),
                ('purchase_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega_taller_linea', to='compras_oil.purchaseline')),
            ],
        ),
    ]
