# Generated by Django 6.0.2 on 2026-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_workshopdelivery_workshopdeliveryline'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdelivery',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshopdeliveryline',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
