# Generated by Django 6.0.2 on 2026-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_workshopdelivery_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdeliveryline',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
