# Generated by Django 6.0.2 on 2026-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_workshopdeliveryline_cantidad_entregada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20),
        ),
    ]
