# Generated by Django 6.0.2 on 2026-04-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0005_purchaseline_bom_item'),
        ('inventario', '0005_alter_inventoryreceptionline_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceptionline',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreceptionline',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreceptionline',
            name='unidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='cantidad_esperada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='observacion_inventario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='purchase_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras_oil.purchaseline'),
        ),
    ]
