# Generated by Django 6.0.2 on 2026-08-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_oil', '0007_alter_purchaseline_porcentaje_pago_and_more'),
        ('inventario', '0006_inventoryreceptionline_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreceptionline',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='inventoryreceptionline',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='inventoryreceptionline',
            name='unidad',
        ),
        migrations.AddField(
            model_name='workshopdelivery',
            name='destino',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('CAMPO', 'Campo'), ('INVENTARIO', 'Inventario / despacho al cliente')], default='TALLER', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='cantidad_esperada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='purchase_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_linea', to='compras_oil.purchaseline'),
        ),
    ]
