# Generated by Django 6.0.2 on 2026-08-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_inventoryreceptionline_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceptionline',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryreceptionline',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryreceptionline',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryreceptionline',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20),
        ),
    ]
