# Generated by Django 6.0.2 on 2026-08-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_inventoryreceptionline_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreception',
            name='notificacion_100_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreception',
            name='notificacion_80_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
