# Generated by Django 6.0.2 on 2026-09-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_inventory_stock_kardex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdelivery',
            name='destino',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('CAMPO', 'Campo'), ('INVENTARIO', 'Despacho / cliente')], default='TALLER', max_length=20),
        ),
    ]
