# Generated by Django 6.0.2 on 2026-09-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paw_numero', models.CharField(blank=True, db_index=True, max_length=50)),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('accion', models.CharField(db_index=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['paw_numero', '-fecha'], name='auditoria_m_paw_num_e63ddd_idx'), models.Index(fields=['modulo', '-fecha'], name='auditoria_m_modulo_33bfb0_idx')],
            },
        ),
    ]
