# Generated by Django 6.0.2 on 2026-02-05 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paw', models.CharField(max_length=50, unique=True, verbose_name='Número PAW')),
                ('numero_cotizacion', models.CharField(blank=True, max_length=50, verbose_name='Número de cotización')),
                ('cliente', models.CharField(max_length=120)),
                ('campo', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(max_length=120)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paws_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
