# Generated by Django 6.0.2 on 2026-02-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paw',
            name='tipo',
        ),
        migrations.AddField(
            model_name='paw',
            name='nombre_paw',
            field=models.CharField(default='PAW SIN NOMBRE', max_length=150, verbose_name='Nombre del PAW'),
            preserve_default=False,
        ),
    ]
