# Generated by Django 6.0.2 on 2026-02-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0002_remove_paw_tipo_paw_nombre_paw'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paws', to='quotes.quotation'),
        ),
    ]
