# Generated by Django 6.0.2 on 2026-02-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0003_paw_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paw',
            name='numero_cotizacion',
        ),
    ]
