# Generated by Django 6.0.2 on 2026-02-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0004_remove_paw_numero_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='cliente',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
