# Generated by Django 6.0.2 on 2026-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0005_alter_paw_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='nombre_paw',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del PAW'),
        ),
        migrations.AlterField(
            model_name='paw',
            name='numero_paw',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número PAW'),
        ),
    ]
