# Generated by Django 6.0.2 on 2026-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0006_alter_paw_nombre_paw_alter_paw_numero_paw'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='estado_operativo',
            field=models.CharField(choices=[('PAW_CREADO', 'PAW creado'), ('OT_CREADA', 'OT creada'), ('BOM_CREADO', 'BOM creado'), ('EN_COMPRAS', 'En compras'), ('EN_FINANZAS', 'En finanzas'), ('EN_APROBACION', 'En aprobación'), ('PAGO_OK', 'Pago OK'), ('MATERIAL_RECIBIDO', 'Material recibido'), ('ENTREGADO_TALLER', 'Entregado a taller'), ('PRODUCTO_OK', 'Producto OK'), ('EN_FACTURACION', 'En facturación'), ('FACTURADO', 'Facturado'), ('RADICADO', 'Radicado')], default='PAW_CREADO', max_length=30),
        ),
    ]
