# Generated by Django 6.0.2 on 2026-04-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0007_paw_estado_operativo'),
        ('quotes', '0004_cliente_quotation_cliente_registrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='cotizacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='paws',
                to='quotes.quotation',
            ),
        ),
    ]