# Generated by Django 6.0.2 on 2026-04-29 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0008_alter_paw_cotizacion'),
        ('quotes', '0004_cliente_quotation_cliente_registrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paws', to='quotes.quotation'),
        ),
    ]
