# Generated by Django 6.0.2 on 2026-05-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0008_alter_paw_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='tipo_operacion',
            field=models.CharField(choices=[('ENSAMBLE', 'Ensamble / Taller'), ('SERVICIO_CAMPO', 'Servicio técnico en campo')], default='ENSAMBLE', help_text='Use Servicio técnico en campo cuando el PAW no requiere ensamble en taller.', max_length=30, verbose_name='Tipo de operación'),
        ),
    ]
