# Generated by Django 6.0.2 on 2026-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0009_paw_tipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='criticidad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', help_text='Prioridad manual para revisión en reunión de operaciones.', max_length=10, verbose_name='Criticidad'),
        ),
        migrations.AddField(
            model_name='paw',
            name='estado_gestion',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('PENDIENTE', 'Pendiente')], default='ASIGNADO', help_text='Estado manual para reunión: asignado, en proceso o pendiente.', max_length=20, verbose_name='Estado de gestión'),
        ),
    ]
