# Generated by Django 6.0.2 on 2026-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0010_paw_criticidad_paw_estado_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='requiere_campo',
            field=models.BooleanField(blank=True, help_text='Si está vacío, se conserva la lógica histórica basada en tipo_operacion.', null=True, verbose_name='Requiere servicio en campo'),
        ),
        migrations.AddField(
            model_name='paw',
            name='requiere_compras',
            field=models.BooleanField(blank=True, help_text='Si está vacío, el flujo actual de compras no se modifica todavía.', null=True, verbose_name='Requiere compras / materiales'),
        ),
        migrations.AddField(
            model_name='paw',
            name='requiere_taller',
            field=models.BooleanField(blank=True, help_text='Si está vacío, se conserva la lógica histórica basada en tipo_operacion.', null=True, verbose_name='Requiere taller / ensamble'),
        ),
        migrations.AlterField(
            model_name='paw',
            name='tipo_operacion',
            field=models.CharField(choices=[('ENSAMBLE', 'Ensamble / Taller'), ('SERVICIO_CAMPO', 'Servicio técnico en campo')], default='ENSAMBLE', help_text='Campo legado. Se conserva para no afectar los PAW existentes durante la transición.', max_length=30, verbose_name='Tipo de operación'),
        ),
    ]
