# Generated by Django 6.0.2 on 2026-08-25 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0011_paw_requiere_campo_paw_requiere_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='public_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Token público de seguimiento'),
        ),
        migrations.AddField(
            model_name='paw',
            name='seguimiento_publico_activo',
            field=models.BooleanField(default=False, verbose_name='Seguimiento público activo'),
        ),
        migrations.AddField(
            model_name='paw',
            name='seguimiento_publico_vence',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento del seguimiento público'),
        ),
    ]
