# Generated by Django 6.0.2 on 2026-08-25 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0012_paw_public_token_paw_seguimiento_publico_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público de seguimiento'),
        ),
    ]
