from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies=[('pricing','0007_consumables_policy'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='CifConfig',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nombre',models.CharField(default='CIF / Costos indirectos',max_length=140)),('horas_productivas_base_mes',models.DecimalField(decimal_places=2,default=176,help_text='Horas-hombre productivas mensuales usadas como base para distribuir el pool CIF.',max_digits=10)),('activo',models.BooleanField(default=True)),('actualizado_en',models.DateTimeField(auto_now=True)),('actualizado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='cif_config_actualizada',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='CifItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('categoria',models.CharField(choices=[('PERSONAL','Personal indirecto'),('INSTALACIONES','Instalaciones / servicios'),('HSE','HSE / seguridad industrial'),('MANTENIMIENTO','Mantenimiento general'),('ADMIN','Administrativo'),('OTRO','Otro indirecto')],default='PERSONAL',max_length=20)),('concepto',models.CharField(max_length=160)),('costo_mes',models.DecimalField(decimal_places=2,default=0,max_digits=18)),('participacion_pct',models.DecimalField(decimal_places=2,default=100,help_text='Porcentaje del costo mensual atribuible a la operación HPS/taller.',max_digits=6)),('activo',models.BooleanField(default=True)),('observacion',models.CharField(blank=True,default='',max_length=240)),('configuracion',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='conceptos',to='pricing.cifconfig'))]),
        migrations.CreateModel(name='CifConfigHistory',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('datos',models.JSONField(default=dict)),('costo_indirecto_mes',models.DecimalField(decimal_places=2,default=0,max_digits=18)),('tarifa_hora',models.DecimalField(decimal_places=2,default=0,max_digits=18)),('vigente_desde',models.DateTimeField(default=django.utils.timezone.now)),('configuracion',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='historial',to='pricing.cifconfig')),('registrado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-vigente_desde']}),
    ]
