# Generated by Django 6.0.2 on 2026-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_cif_base_automatica_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalcost',
            name='tipo',
            field=models.CharField(choices=[('MANO_OBRA', 'Mano de obra'), ('BANCO', 'Banco de prueba / QA-QC'), ('CONSUMIBLES', 'Consumibles generales'), ('FLETE', 'Transporte / movilización'), ('VIATICOS', 'Viáticos'), ('CIF', 'CIF / costos indirectos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricecalculationline',
            name='tipo',
            field=models.CharField(choices=[('INSUMO', 'Insumo / repuesto'), ('MANO_OBRA', 'Mano de obra'), ('MECANIZADO', 'Mecanizado / terceros'), ('BANCO', 'Banco de prueba / QA-QC'), ('CONSUMIBLE', 'Consumibles'), ('FLETE', 'Transporte / movilización'), ('VIATICOS', 'Viáticos'), ('CIF', 'CIF / costos indirectos'), ('SERVICIO', 'Servicio / costo directo'), ('OTRO', 'Otro costo')], default='INSUMO', max_length=12),
        ),
    ]
