# Generated by Django 6.0.2 on 2026-04-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Periodo de venta',
                'verbose_name_plural': 'Periodos de venta',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('tipo_prenda', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DEBE', 'Debe'), ('ABONADO', 'Abonado'), ('PAGADO', 'Pagado')], default='DEBE', max_length=10)),
                ('valor_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_deber', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.periodoventa')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
    ]
