# Generated by Django 6.0.2 on 2026-02-24 16:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paw_app', '0005_alter_paw_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('presupuesto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='paw_app.paw')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
