# Generated by Django 6.0.2 on 2026-09-22 00:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre de la familia')),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('role', models.CharField(choices=[('OWNER', 'Propietario y aprobador'), ('ADMIN', 'Administrador familiar'), ('CHILD', 'Hijo/a')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_membership', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family_finance.household')),
            ],
            options={
                'verbose_name': 'miembro familiar',
                'verbose_name_plural': 'miembros familiares',
                'ordering': ['role', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('FIXED', 'Gasto fijo'), ('VARIABLE', 'Gasto variable'), ('CHILD', 'Presupuesto personal'), ('DEBT', 'Deuda'), ('SAVINGS', 'Ahorro')], max_length=10)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='family_finance.household')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='año')),
                ('month', models.PositiveSmallIntegerField(verbose_name='mes')),
                ('status', models.CharField(choices=[('DRAFT', 'En preparación'), ('ACTIVE', 'Activo'), ('CLOSED', 'Cerrado')], default='ACTIVE', max_length=10)),
                ('savings_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='meta de ahorro')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_plans', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='family_finance.household')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ingreso')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor esperado')),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor recibido')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='fecha esperada')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='fecha recibida')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='family_finance.monthlyplan')),
            ],
            options={
                'ordering': ['expected_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='obligación')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor presupuestado')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor pagado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vencimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido')], default='PENDING', max_length=10)),
                ('recurring', models.BooleanField(default=True, verbose_name='repetir cada mes')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_finance.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_expenses', to='family_finance.monthlyplan')),
            ],
            options={
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='qué deseas comprar')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor solicitado')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor aprobado')),
                ('reason', models.TextField(verbose_name='por qué lo necesitas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10)),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='respuesta')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_finance.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_extra_requests', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_requests', to='family_finance.familymembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_requests', to='family_finance.monthlyplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor')),
                ('date', models.DateField(verbose_name='fecha')),
                ('source', models.CharField(choices=[('NEQUI', 'Nequi'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('BANK', 'Cuenta bancaria')], max_length=10)),
                ('receipt', models.FileField(blank=True, upload_to='familia/comprobantes/%Y/%m/', verbose_name='comprobante')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_finance.category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='family_finance.familymembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='family_finance.monthlyplan')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='meta de gasto')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='meta o explicación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_finance.category')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='family_finance.monthlyplan')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado para aprobación'), ('APPROVED', 'Aprobado'), ('CHANGES', 'Requiere ajustes'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=12)),
                ('child_message', models.TextField(blank=True, verbose_name='mensaje')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='comentario del aprobador')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_budgets', to='family_finance.familymembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_budgets', to='family_finance.monthlyplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_family_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='para qué lo necesitas')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor solicitado')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor aprobado')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='explicación')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='family_finance.personalbudget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_finance.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='meta')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor objetivo')),
                ('saved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor ahorrado')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='fecha objetivo')),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='family_finance.household')),
            ],
            options={
                'ordering': ['target_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor transferido')),
                ('date', models.DateField(verbose_name='fecha')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('CONFIRMED', 'Confirmado por el hijo')], default='SENT', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='nota')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfers', to='family_finance.familymembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfers', to='family_finance.monthlyplan')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('household', 'name', 'kind'), name='unique_family_category'),
        ),
        migrations.AddConstraint(
            model_name='monthlyplan',
            constraint=models.UniqueConstraint(fields=('household', 'year', 'month'), name='unique_family_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyplan',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='valid_family_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetallocation',
            constraint=models.UniqueConstraint(fields=('plan', 'category'), name='unique_month_category_budget'),
        ),
        migrations.AddConstraint(
            model_name='personalbudget',
            constraint=models.UniqueConstraint(fields=('plan', 'member'), name='unique_personal_month_budget'),
        ),
    ]
