# Generated by Django 6.0.2 on 2026-09-01 04:07

import django.db.models.deletion
import internal_chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=internal_chat.models.ruta_adjunto_chat)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=150)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='internal_chat.mensaje')),
            ],
        ),
    ]
