# Generated by Django 6.0.2 on 2026-09-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_chat', '0002_adjuntomensaje'),
        ('paw_app', '0013_alter_paw_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='paw',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversacion_chat', to='paw_app.paw'),
        ),
    ]
