# Generated by Django 6.0.2 on 2026-02-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad Medida')),
                ('clasificacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Clasificación')),
                ('grupo_inventario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Inventario')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Oil & Gas',
                'verbose_name_plural': 'Items Oil & Gas',
                'ordering': ['codigo'],
            },
        ),
    ]
