# Generated by Django 6.0.2 on 2026-02-18 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paw_app', '0005_alter_paw_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=120)),
                ('numero_factura', models.CharField(max_length=60, unique=True)),
                ('numero_servicio', models.CharField(max_length=60)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_radicacion', models.DateField(default=django.utils.timezone.now)),
                ('tipo_pago', models.CharField(choices=[('directo', 'Directo'), ('endoso', 'Endoso')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paw', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='paw_app.paw')),
            ],
        ),
    ]
