# Generated by Django 6.0.2 on 2026-02-18 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_estado_alter_factura_fecha_radicacion_and_more'),
        ('item_oil_gas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='municipio',
        ),
        migrations.AddField(
            model_name='factura',
            name='item_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='item_oil_gas.item', verbose_name='Item factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Lugar de entrega'),
        ),
        migrations.AddField(
            model_name='factura',
            name='lugar_servicio',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Lugar de servicio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('radicacion', 'Radicación'), ('facturado', 'Facturado'), ('vencida', 'Vencida')], default='radicacion', max_length=12, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_radicacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha radicación'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Número factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_servicio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Número de servicio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('directo', 'Directo'), ('endoso', 'Endoso')], max_length=10, null=True, verbose_name='Tipo de pago'),
        ),
    ]
