# Generated by Django 6.0.2 on 2026-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_factura_municipio_factura_item_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('radicacion', 'Radicación'), ('facturado', 'Facturado'), ('vencida', 'Vencida'), ('pagada', 'Pagada')], default='radicacion', max_length=12, verbose_name='Estado'),
        ),
    ]
