# Generated by Django 6.0.2 on 2026-04-30 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_fecha_pago_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_radicacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha radicación'),
        ),
    ]
