# Generated by Django 6.0.2 on 2026-02-19 15:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras_oil', '0005_purchaseline_bom_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_approvals_enviados', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_approval', to='compras_oil.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('cantidad_a_comprar', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('tipo_pago', models.CharField(blank=True, max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('valor_unidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('observaciones', models.TextField(blank=True)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('observacion_finanzas', models.TextField(blank=True)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='aprobacion.purchaseapproval')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('purchase_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_approval_line', to='compras_oil.purchaseline')),
            ],
            options={
                'indexes': [models.Index(fields=['estado_aprobacion'], name='aprobacion__estado__f00890_idx')],
            },
        ),
    ]
