# Generated by Django 6.0.2 on 2026-05-05 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paw_app', '0008_alter_paw_cotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='EN_CURSO', max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paw', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='servicio_campo', to='paw_app.paw')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_campo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldServiceDailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('dia_numero', models.PositiveIntegerField(default=1)),
                ('transporte', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comunidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('alojamiento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('personas', models.PositiveIntegerField(default=1)),
                ('tarifa_alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('hidratacion_por_persona', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('vuelo_ida_aplica', models.BooleanField(default=False)),
                ('vuelo_ida_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vuelo_regreso_aplica', models.BooleanField(default=False)),
                ('vuelo_regreso_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gastos_adicionales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='campo.fieldservice')),
            ],
            options={
                'ordering': ['fecha', 'dia_numero'],
            },
        ),
    ]
