# Generated by Django 6.0.2 on 2026-05-05 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldservice',
            options={'ordering': ['-actualizado_en'], 'verbose_name': 'Servicio de campo', 'verbose_name_plural': 'Servicios de campo'},
        ),
        migrations.AlterModelOptions(
            name='fieldservicedailyexpense',
            options={'ordering': ['fecha', 'dia_numero', 'id'], 'verbose_name': 'Gasto diario de campo', 'verbose_name_plural': 'Gastos diarios de campo'},
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_campo_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldservice',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_campo_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
