# Generated by Django 6.0.2 on 2026-05-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_alter_fieldservice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldservicedailyexpense',
            name='comunidad',
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='apoyo_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Permisos, guías, accesos, apoyo comunitario o logística local.', max_digits=14, verbose_name='Apoyo local / comunidad'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='alojamiento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor unitario por persona.', max_digits=14, verbose_name='Alojamiento por persona'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='tarifa_alimentacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Alimentación por persona'),
        ),
    ]
