# Generated by Django 6.0.2 on 2026-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_remove_fieldservicedailyexpense_comunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='actividades',
            field=models.TextField(blank=True, help_text='Resumen técnico de actividades realizadas durante el día. No incluir valores económicos.', verbose_name='Actividades realizadas'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='alojamiento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor unitario por persona. El sistema lo multiplica por personas.', max_digits=14, verbose_name='Alojamiento unitario'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='apoyo_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Apoyo local / comunidad'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='tarifa_alimentacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
