# Generated by Django 6.0.2 on 2026-05-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0004_fieldservicedailyexpense_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldservice',
            name='especialista_apoyo',
            field=models.CharField(blank=True, choices=[('Carlos Hende', 'Carlos Hende'), ('Reison Vanegas', 'Reison Vanegas'), ('Yeferson Muñoz', 'Yeferson Muñoz'), ('Sergio Ortiz', 'Sergio Ortiz'), ('Jose Oyola', 'Jose Oyola')], default='', max_length=100, verbose_name='Especialista apoyo'),
        ),
        migrations.AddField(
            model_name='fieldservice',
            name='especialista_lider',
            field=models.CharField(blank=True, choices=[('Carlos Hende', 'Carlos Hende'), ('Reison Vanegas', 'Reison Vanegas'), ('Yeferson Muñoz', 'Yeferson Muñoz'), ('Sergio Ortiz', 'Sergio Ortiz'), ('Jose Oyola', 'Jose Oyola')], default='', max_length=100, verbose_name='Especialista líder'),
        ),
    ]
