# Generated by Django 6.0.2 on 2026-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0005_fieldservice_especialista_apoyo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='dia_trabajado_campo',
            field=models.BooleanField(default=True, help_text='Marcar cuando el personal trabajó en campo y aplica bono según rol.', verbose_name='Día trabajado en campo'),
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='regreso_despues_6pm',
            field=models.BooleanField(default=False, help_text='Si ya trabajó el día, suma movilización adicional por persona.', verbose_name='Regreso después de las 6:00 pm'),
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='salida_despues_mediodia',
            field=models.BooleanField(default=False, help_text='Si solo hubo salida después de las 12:00, no aplica bono campo; aplica movilización.', verbose_name='Salida después del mediodía'),
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='solo_viaje_traslado',
            field=models.BooleanField(default=False, help_text='Día sin trabajo en campo. Solo aplica movilización por persona.', verbose_name='Solo viaje / traslado'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='apoyo_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Campo legado. Ya no se captura en el formulario.', max_digits=14, verbose_name='Apoyo local / comunidad (legado)'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='personas',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de personas para gastos operativos como alojamiento, alimentación e hidratación.'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='transporte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor manual que cobra la operación/comunidad por movilización diaria.', max_digits=14, verbose_name='Transporte comunidad / operación'),
        ),
    ]
