# Generated by Django 6.0.2 on 2026-05-11 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0006_fieldservicedailyexpense_dia_trabajado_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='aprobado_por',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Jose Oyola', 'Jose Oyola'), ('Marcela Cutiva', 'Marcela Cutiva'), ('Gerencia', 'Gerencia')], default='', help_text='Registro informativo. No genera flujo de aprobación.', max_length=120, verbose_name='Quién aprobó'),
        ),
        migrations.AddField(
            model_name='fieldservicedailyexpense',
            name='comprado_por',
            field=models.CharField(blank=True, default='', help_text='Registro informativo. No genera flujo de aprobación.', max_length=120, verbose_name='Quién compró'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='alojamiento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Campo legado. En registros nuevos se captura por persona.', max_digits=14, verbose_name='Alojamiento unitario'),
        ),
        migrations.AlterField(
            model_name='fieldservicedailyexpense',
            name='personas',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de personas para habilitar el detalle individual de gastos.'),
        ),
        migrations.CreateModel(
            name='FieldServicePersonExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=120, verbose_name='Persona / técnico')),
                ('clasificacion', models.CharField(choices=[('DIA_TRABAJADO_CAMPO', 'Día trabajado en campo'), ('SALIDA_DESPUES_MEDIODIA', 'Salida después del mediodía'), ('REGRESO_DESPUES_6PM', 'Regreso después de las 6:00 pm'), ('SOLO_VIAJE_TRASLADO', 'Solo viaje / traslado')], default='DIA_TRABAJADO_CAMPO', max_length=40, verbose_name='Clasificación operativa')),
                ('alojamiento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lavanderia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transporte_personal', models.DecimalField(decimal_places=2, default=0, help_text='Taxi, transporte al aeropuerto u otros transportes personales.', max_digits=14, verbose_name='Transporte personal')),
                ('vuelo_ida_aplica', models.BooleanField(default=False)),
                ('vuelo_ida_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vuelo_regreso_aplica', models.BooleanField(default=False)),
                ('vuelo_regreso_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.CharField(blank=True, default='', max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('gasto_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_personas', to='campo.fieldservicedailyexpense')),
            ],
            options={
                'verbose_name': 'Gasto por persona de campo',
                'verbose_name_plural': 'Gastos por persona de campo',
                'ordering': ['id'],
            },
        ),
    ]
