# Generated by Django 6.0.2 on 2026-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0007_fieldservicedailyexpense_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldservicepersonexpense',
            name='dia_trabajado_campo',
            field=models.BooleanField(default=True, verbose_name='Día trabajado en campo'),
        ),
        migrations.AddField(
            model_name='fieldservicepersonexpense',
            name='regreso_despues_6pm',
            field=models.BooleanField(default=False, verbose_name='Regreso después de las 6:00 pm'),
        ),
        migrations.AddField(
            model_name='fieldservicepersonexpense',
            name='salida_despues_mediodia',
            field=models.BooleanField(default=False, verbose_name='Salida después del mediodía'),
        ),
        migrations.AddField(
            model_name='fieldservicepersonexpense',
            name='solo_viaje_traslado',
            field=models.BooleanField(default=False, verbose_name='Solo viaje / traslado'),
        ),
    ]
