# Generated by Django 6.0.2 on 2026-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0012_apoyos_multiples_hidratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldservicepersonexpense',
            name='hidratacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
