"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# Seguridad / Entorno
# =========================

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-me")

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    ""
).split(",")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in CSRF_TRUSTED_ORIGINS
    if o.strip()
]


# =========================
# Apps
# =========================

INSTALLED_APPS = [
    "daphne",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "channels",
    "storages",
    "internal_chat.apps.InternalChatConfig",

    "accounts.apps.AccountsConfig",
    "bom",
    "workorders",
    "paw_app",
    "quotes",
    "compras_oil",
    "finanzas",
    "inventario",
    "item_oil_gas",
    "facturacion",
    "aprobacion",
    "historial",
    "presupuesto.apps.PresupuestoConfig",
    "ventas",
    "dashboard",
    "taller",
    "campo",
]


# =========================
# Middleware
# =========================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


# =========================
# Templates
# =========================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# =========================
# Database (SQLite local / Postgres en Render)
# =========================

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# =========================
# Password validation
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator"
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]


# =========================
# Internationalization
# =========================

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Bogota"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# =========================
# Static files
# =========================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# =========================
# Media files - Cloudflare R2
# =========================

R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "")
R2_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL", "")

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": R2_ACCESS_KEY_ID,
            "secret_key": R2_SECRET_ACCESS_KEY,
            "bucket_name": R2_BUCKET_NAME,
            "endpoint_url": R2_ENDPOINT_URL,
            "region_name": "auto",
            "default_acl": None,
            "querystring_auth": True,
            "file_overwrite": False,
        },
    },
    "staticfiles": {
        "BACKEND":
        "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =========================
# Default PK
# =========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# Render / Proxy SSL
# =========================

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# =========================
# Telegram Bot
# =========================

TG_BOT_TOKEN = os.environ.get("TG_BOT_TOKEN", "")
TG_ENABLED = (
    os.environ.get("TG_ENABLED", "True").lower()
    == "true"
)


# =========================
# Correo / Notificaciones
# =========================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(
    os.environ.get("EMAIL_PORT", "587")
)
EMAIL_USE_TLS = (
    os.environ.get("EMAIL_USE_TLS", "True").lower()
    == "true"
)
EMAIL_USE_SSL = (
    os.environ.get("EMAIL_USE_SSL", "False").lower()
    == "true"
)

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "operaciones@oilgassupport.com",
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "IMPETUS CONTROL <operaciones@oilgassupport.com>",
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL

IMPETUS_CONTROL_URL = os.environ.get(
    "IMPETUS_CONTROL_URL",
    "https://www.impetuscontrol.com",
)


# =========================
# AUTH (login)
# =========================

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"


# =========================
# Django Channels / Redis-Valkey
# =========================

REDIS_URL = os.environ.get("REDIS_URL", "")

if REDIS_URL:
    # Producción (Render): usa Key Value / Valkey.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND":
            "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Desarrollo local: no requiere Redis.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND":
            "channels.layers.InMemoryChannelLayer",
        },
    }
