# Generated by Django 6.0.2 on 2026-02-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0004_workorder_paw'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITUD', 'Solicitud Inventario')], default='BORRADOR', max_length=12)),
                ('comentarios', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitado_en', models.DateTimeField(blank=True, null=True)),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bom', to='workorders.workorder')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='bom.bomtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad_estandar', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bom')),
            ],
        ),
        migrations.CreateModel(
            name='BomTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad_estandar', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bomtemplate')),
            ],
            options={
                'unique_together': {('template', 'descripcion', 'codigo')},
            },
        ),
    ]
