# Generated by Django 6.0.2 on 2026-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='plano',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
