# Generated by Django 6.0.2 on 2026-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_bomitem_observaciones_bomitem_plano'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bomtemplateitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bomtemplateitem',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bomtemplateitem',
            name='plano',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='bomtemplateitem',
            unique_together={('template', 'descripcion', 'codigo', 'plano')},
        ),
    ]
