# Generated by Django 6.0.2 on 2026-08-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_alter_bomtemplateitem_unique_together_and_more'),
        ('item_oil_gas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='grupo_inventario',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='item_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_items', to='item_oil_gas.item'),
        ),
    ]
