# Generated by Django 6.0.2 on 2026-08-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_bomitem_clasificacion_bomitem_grupo_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomitem',
            name='item_catalogo',
        ),
    ]
