# Generated by Django 6.0.2 on 2026-08-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paw_app', '0010_paw_criticidad_paw_estado_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamaraTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('serial', models.CharField(db_index=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('PENDIENTE_TD', 'Pendiente Tear Down'), ('TD_REALIZADO', 'Tear Down realizado'), ('PENDIENTE_COTIZACION', 'Pendiente cotización'), ('COTIZACION_ENVIADA', 'Cotización enviada'), ('PENDIENTE_APROBACION', 'Pendiente aprobación'), ('APROBADA', 'Aprobada / Pendiente PAW'), ('PAW_GENERADO', 'PAW generado')], default='RECIBIDA', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camaras_taller', to='paw_app.paw')),
            ],
        ),
    ]
