# Generated by Django 6.0.2 on 2026-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarataller',
            name='marca',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
