# Generated by Django 6.0.2 on 2026-08-12 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_camarataller_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsambleTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='EN_CURSO', max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('camara', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ensamble_taller', to='taller.camarataller')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ensambles_taller_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ensamble de taller',
                'verbose_name_plural': 'Ensambles de taller',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='EnsambleTallerTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(choices=[('Carlos Hende', 'Carlos Hende'), ('Reison Vanegas', 'Reison Vanegas'), ('Yeferson Muñoz', 'Yeferson Muñoz'), ('Sergio Ortiz', 'Sergio Ortiz'), ('Jose Oyola', 'Jose Oyola')], max_length=120, verbose_name='Técnico')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ensamble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='taller.ensambletaller')),
            ],
            options={
                'verbose_name': 'Técnico de ensamble',
                'verbose_name_plural': 'Técnicos de ensamble',
                'ordering': ['tecnico'],
            },
        ),
        migrations.CreateModel(
            name='JornadaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('actividades', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('horas_ordinarias', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('horas_extra_diurna', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('horas_extra_nocturna', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('horas_totales', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ensamble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='taller.ensambletaller')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_taller_registradas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='taller.ensambletallertecnico')),
            ],
            options={
                'verbose_name': 'Jornada de taller',
                'verbose_name_plural': 'Jornadas de taller',
                'ordering': ['fecha', 'hora_entrada', 'tecnico__tecnico', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ensambletallertecnico',
            constraint=models.UniqueConstraint(fields=('ensamble', 'tecnico'), name='uniq_tecnico_por_ensamble_taller'),
        ),
        migrations.AddConstraint(
            model_name='jornadataller',
            constraint=models.UniqueConstraint(fields=('ensamble', 'tecnico', 'fecha', 'hora_entrada'), name='uniq_inicio_jornada_tecnico_taller'),
        ),
    ]
