# Generated by Django 6.0.2 on 2026-08-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0010_paw_criticidad_paw_estado_gestion'),
        ('taller', '0003_ensambletaller_ensambletallertecnico_jornadataller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensambletaller',
            name='camara',
        ),
        migrations.AddField(
            model_name='ensambletaller',
            name='paw',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ensamble_horas_taller', to='paw_app.paw'),
        ),
    ]
