# Generated by Django 6.0.2 on 2026-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_remove_ensambletaller_camara_ensambletaller_paw'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarataller',
            name='fecha_tear_down',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Tear Down'),
        ),
    ]
