# Generated by Django 6.0.2 on 2026-02-05 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.CharField(blank=True, max_length=120)),
                ('equipo', models.CharField(blank=True, max_length=120)),
                ('serial', models.CharField(blank=True, max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En proceso'), ('EN_ESPERA', 'En espera'), ('TERMINADA', 'Terminada'), ('CERRADA', 'Cerrada')], default='NUEVA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ot_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('HECHA', 'Hecha')], default='PENDIENTE', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='workorders.workorder')),
            ],
        ),
    ]
