# Generated by Django 6.0.2 on 2026-02-05 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='asignado_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ot_asignadas_grupo', to='auth.group'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='iniciado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='terminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='visibilidad',
            field=models.CharField(choices=[('PUBLICA', 'Pública (todos la ven)'), ('RESTRINGIDA', 'Restringida (solo asignados)')], default='RESTRINGIDA', max_length=15),
        ),
    ]
