# Generated by Django 6.0.2 on 2026-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_asignado_grupo_workorder_iniciado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='comentario_taller',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='etapa_taller',
            field=models.CharField(blank=True, choices=[('DESARME', 'Desarme'), ('ALISTAMIENTO', 'Alistamiento'), ('ENSAMBLANDO', 'Ensamblando'), ('PRUEBA', 'Prueba')], max_length=20, null=True),
        ),
    ]
