# Generated by Django 6.0.2 on 2026-02-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0002_remove_paw_tipo_paw_nombre_paw'),
        ('workorders', '0003_workorder_comentario_taller_workorder_etapa_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='paw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ots', to='paw_app.paw'),
        ),
    ]
