# Generated by Django 6.0.2 on 2026-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorder_paw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='etapa_taller',
            field=models.CharField(blank=True, choices=[('DESARME', 'Desarme'), ('ALISTAMIENTO', 'Alistamiento'), ('ENSAMBLANDO', 'Ensamblando'), ('TERMINADO', 'Terminado')], max_length=20, null=True),
        ),
    ]
