# Generated by Django 6.0.2 on 2026-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_alter_workorder_etapa_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
