# Generated by Django 6.0.2 on 2026-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_workorder_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='ensamble_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='fecha_ensamble_ok',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
