# Generated by Django 6.0.2 on 2026-05-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_fix_ensamble_fields'),
        ('workorders', '0010_state_ensamble_confirmado_por'),
    ]

    operations = [
    ]
