# Generated by Django 6.0.2 on 2026-02-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.PositiveBigIntegerField()),
                ('closed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-closed_at'],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_historial_content_object')],
            },
        ),
    ]
