from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("compras_oil", "0011_purchase_request_stock")]
    operations = [
        migrations.CreateModel(name="HSEStock", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("catalogo", models.CharField(default="IMPETUS", max_length=20)), ("catalogo_item_id", models.PositiveIntegerField()), ("codigo", models.CharField(db_index=True, max_length=80)), ("descripcion", models.CharField(max_length=300)), ("unidad", models.CharField(default="UND", max_length=30)), ("cantidad_fisica", models.DecimalField(decimal_places=3, default=0, max_digits=14)), ("actualizado_en", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="HSERequest", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("tipo", models.CharField(choices=[("EPP", "Entrega de EPP"), ("DOTACION", "Entrega de dotación")], max_length=12)), ("estado", models.CharField(choices=[("PENDIENTE", "Pendiente de Inventario"), ("EN_COMPRAS", "En compras"), ("LISTA", "Lista para entregar"), ("ENTREGADA", "Entregada"), ("CANCELADA", "Cancelada")], default="PENDIENTE", max_length=16)), ("observacion", models.TextField(blank=True)), ("creado_en", models.DateTimeField(auto_now_add=True)), ("actualizado_en", models.DateTimeField(auto_now=True)), ("entregado_en", models.DateTimeField(blank=True, null=True)), ("compra", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="solicitud_hse", to="compras_oil.purchaserequest")), ("empleado", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hse_solicitudes_recibidas", to=settings.AUTH_USER_MODEL)), ("entregado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="hse_entregas_realizadas", to=settings.AUTH_USER_MODEL)), ("solicitado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hse_solicitudes_creadas", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="HSERequestLine", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("catalogo", models.CharField(default="IMPETUS", max_length=20)), ("catalogo_item_id", models.PositiveIntegerField()), ("codigo", models.CharField(max_length=80)), ("descripcion", models.CharField(max_length=300)), ("unidad", models.CharField(default="UND", max_length=30)), ("cantidad_solicitada", models.DecimalField(decimal_places=3, default=1, max_digits=12)), ("cantidad_entregada", models.DecimalField(decimal_places=3, default=0, max_digits=12)), ("solicitud", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lineas", to="hse.hserequest"))]),
        migrations.CreateModel(name="HSEMovement", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("tipo", models.CharField(choices=[("RECEPCION", "Recepción en bodega HSE"), ("ENTREGA", "Entrega al empleado"), ("AJUSTE", "Ajuste de bodega HSE")], max_length=12)), ("cantidad", models.DecimalField(decimal_places=3, max_digits=14)), ("saldo_anterior", models.DecimalField(decimal_places=3, max_digits=14)), ("saldo_nuevo", models.DecimalField(decimal_places=3, max_digits=14)), ("referencia", models.CharField(blank=True, max_length=80)), ("creado_en", models.DateTimeField(auto_now_add=True)), ("creado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("stock", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimientos", to="hse.hsestock"))]),
        migrations.AddConstraint(model_name="hsestock", constraint=models.UniqueConstraint(fields=("catalogo", "catalogo_item_id"), name="hse_stock_catalogo_item")),
    ]
