# Generated by Django 6.0.2 on 2026-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, unique=True, verbose_name='Número de cotización')),
                ('nombre_cotizacion', models.CharField(max_length=150, verbose_name='Nombre de cotización')),
                ('cliente', models.CharField(max_length=120)),
                ('campo', models.CharField(blank=True, max_length=120)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ADJUDICADA', 'Adjudicada'), ('EVALUACION', 'Evaluación'), ('CERRADA', 'Cerrada')], default='EVALUACION', max_length=12)),
                ('empresa', models.CharField(choices=[('IMPETUS', 'Impetus'), ('OIL_GAS', 'Oil & Gas')], default='IMPETUS', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
