# Generated by Django 6.0.2 on 2026-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
