# Generated by Django 6.0.2 on 2026-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotation_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
